---
name: Update the index

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - run: go run .
      - run: git config --global --add safe.directory /__w/falco-rules-explorer/falco-rules-explorer
      - uses: EndBug/add-and-commit@v9
        with:
          message: update index of rules
          default_author: github_actions
          commit: --signoff